# Generated by Django 4.1.3 on 2022-11-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('1', 'Full Time'), ('2', 'Part Time')], max_length=300)),
                ('description', models.TextField(max_length=1000)),
                ('vacancy', models.IntegerField(default=1)),
                ('salary', models.IntegerField(default=0)),
                ('exprience', models.IntegerField(default=1)),
            ],
        ),
    ]
